### ISSUE TITLE
zE deletes manual markers

### ISSUE THREAD

**Issue by ghost** [ctechols/vim-HideShow#1]
The zE at the end of DisableHideShow removes any existing fold markers, including any manual markers that happened to be already in the buffer. Maybe there could be a command after it that detects if the zE command modified the buffer, and undo it if so.

**Comment by ctechols** [comment]
Ooops.  I'm sorry about that.  I hope you didn't lose any critical work.

I'm hesitant to use undo, because the change will still be in the undo stack and the user might :redo it and be surprised.

I'm committing a change that uses zN to reset folds.  This doesn't seem to properly restore for all foldmethods, but I have confirmed that it doesn't delete your markers, and I wanted to get a change out quickly so others don't lose their work.
